#pragma once

// Please don't change the content of this header, it is auto generated by CMAKE

#define PROJECT_SOURCE_DIR "C:/Users/CSY/Desktop/CPSC427/CPSC427/project/FlaseAlarm/cpsc-427-dev/template/"
